services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      # - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=123456'
      # - 'MYSQL_USER=myuser'
    ports:
      - 3306:3306
    networks:
      - demo-net
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    networks:
      - demo-net

  zookeeper:
    image: bitnami/zookeeper:3.8.3
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - demo-net

  kafka:
    image: bitnami/kafka:3.6.0
    ports:
      - '9092:9092'
    networks:
      - demo-net
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - /docker-volume/kafka-persistence:/bitnami/kafka/config
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:3.12
    environment:
      - RABBIT_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 8080:15672
    networks:
      - demo-net

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
#      - ELASTIC_USERNAME=elastic
#      - ELASTIC_PASSWORD=123456
#    volumes:
#      - /docker-volume/elasticsearch-persistence/data:/usr/share/elasticsearch/data
#      - /docker-volume/elasticsearch-persistence/plugins:/usr/share/elasticsearch/plugins
    #        - /docker-volume/elasticsearch-persistence/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - demo-net
    privileged: true
  # token:
  # bin/elasticsearch-create-enrollment-token --scope kibana
  # password:
  # bin/elasticsearch-reset-password -u elastic
  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:8.12.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=123456
    ports:
      - 5601:5601
    networks:
      - demo-net
    depends_on:
      - elasticsearch
    privileged: true

networks:
  demo-net:
    name: demo-net
    driver: bridge
    