services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      # - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=123456'
      # - 'MYSQL_USER=myuser'
    ports:
      - 3306:3306
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
