services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      # - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=123456'
      # - 'MYSQL_USER=myuser'
    ports:
      - 3306:3306
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

  kafka:
    image: 'bitnami/kafka:3.6.0'
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
#      - 9093:9093
#      - 29092:29092
    volumes:
      - /docker-volume/kafka-persistence:/bitnami/kafka