server:
  port: 8085
  servlet:
    context-path: 

spring:
  elasticsearch:
    rest:
        uris: https://localhost:9200
#        read-timeout: 10000
#        connection-timeout: 10000
        username: elastic
        password: d=ABgcKOKDxmuSWf4_T_
#        ca-fingerprint: 02D3523FE27FBB1F37E42B43D93A9D8A16A3B7701820B60A7DEF1C52EACD98AB

#   #RabbitMQ服务器配置，地址账号密码，virtualhost等配置
#   rabbitmq:
#     addresses: localhost:15672
#     username: user
#     password: admin
#     virtual-host: 