server:
  port: 8085
  servlet:
    context-path: 

# spring:
#   cache:
#     type: ehcache
#     config: classpath:ehcache.xml

#   #RabbitMQ服务器配置，地址账号密码，virtualhost等配置
#   rabbitmq:
#     addresses: localhost:15672
#     username: user
#     password: admin
#     virtual-host: 