server:
  port: 8085
  servlet:
    context-path: 

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  elasticsearch:
    rest:
        uris: https://localhost:9200
#        read-timeout: 10000
#        connection-timeout: 10000
        username: elastic
        password: d=ABgcKOKDxmuSWf4_T_
#        ca-fingerprint: 02D3523FE27FBB1F37E42B43D93A9D8A16A3B7701820B60A7DEF1C52EACD98AB

kafka:
  topic:
    views-update-topic: views-update-topic
