server:
  port: 8085
  servlet:
    context-path: 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    kafka:
      bootstrap-servers: kafka:9092
      consumer:
        auto-offset-reset: earliest
      producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  elasticsearch:
    rest:
      uris: https://localhost:9200
      #        read-timeout: 10000
      #        connection-timeout: 10000
      username: elastic
      password: d=ABgcKOKDxmuSWf4_T_
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      pool:
        size: 10

springdoc:
  swagger-ui:
    path: /api-docs

kafka:
  topic:
    views-update-topic: views-update-topic

#ApiKeys:
#  OPENAI_API_KEY: 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

langchain4j:
  open-ai:
    chat-model:
      api-key: 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